openapi: 3.0.4
info:
  title: Excel API
  description: .
  version: 0.0.1
paths:
/upload_excel:
    post:
      summary: 
      description: "Save information to local file in XLSX format"
      operationId: upload_excel
      requestBody:
        description: 
        required: true
        content:
          application/json:
            schema:
              $ref: "upload_excel_incoming.schema.json"
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: "upload_excel/upload_excel_responseSuccess.schema.json"
      '500':
        description: Fail
        content:
          application/json:
            schema:
                $ref: "upload_excel/upload_excel_responseFail.schema.json"


/get_excel_files:
    get:
      summary: 
      description: "Get all saved Excel data"
      operationId: get_excel_jsons
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: "get_excel_files/get_excels_responseSuccess.schema.json"
      '404':
        description: Fail
        content:
          application/json:
            schema:
              $ref: "get_excel_files/get_excels_responseFail.schema.json"

/delete_excel:
    delete:
      summary: 
      description: "Delete an Excel file"
      operationId: delete_excel
      requestBody:
        description: 
        required: true
        content:
          application/json:
            schema:
              $ref: "delete_excel/delete_excel_request.schema.json"
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: "delete_excel/delete_excel_responseSuccess.schema.json"
      '500':
        description: Deletion failed
        content:
          application/json:
            schema:
              $ref: "delete_excel/delete_excel_responseFail.schema.json"
      '404':
        description: File not found
        content:
          application/json:
            schema:
              $ref: "delete_excel/delete_excel_responseFail.schema.json"

/get_route:
    get:
      summary: 
      description: "Get all saved routes"
      operationId: get_excel_routes
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: "get_excel_files/get_route_response.schema.json"