name: TMS CI

on: [push]

jobs:
  automated_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch name
        run: echo "Running tests on branch ${{ github.ref }}"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ls ${{ github.workspace }}

      - name: Installing dependencies on frontend
        run: npm install

      - name: Setting up Flask backend
        working-directory: flask-server-test
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Starting frontend (port 3000)
        run: npm run dev &

      - name: Starting Flask backend (port 8000)
        working-directory: flask-server-test
        run: |
          source venv/bin/activate
          python main.py &

      - name: Run smoke tests
        run: CYPRESS_BASE_URL="http://localhost:3000" npm run test:smoke
      
      - name: Run unit tests
        run: npm run test:unit

      - name: Run flask backend tests
        working-directory: react-front-test
        run: |
          npm run install-all
          npm run start